services:
  db:
    image: postgres:16
    container_name: forge_db
    environment:
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: forgepassword
      POSTGRES_DB: forge
    ports:
      - "5433:5432"
    volumes:
      - forge_pgdata:/var/lib/postgresql/data

volumes:
  forge_pgdata:
